import type { Metadata } from "next";
import "./css/globals.css";
import Nav from "./components/Nav";

export const metadata: Metadata = {
  title: "eeeeee eeee eee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="overflow-hidden">
        <Nav
          links={[
            {
              href: "/dashboard",
              label: "Home"
            },
            {
              href: "/dashboard/ball",
              label: "Ball"
            },
            {
              href: "/dashboard/hello",
              label: "Spin"
            }
          ]}
        />
        {children}
      </body>
    </html>
  );
}
